apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
    team: database
    tags.datadoghq.com/service: redis
    tags.datadoghq.com/version: '6.2'
  annotations:
    tags.datadoghq.com/git.repository_url: https://github.com/Norawit2907/DataDog-Poc.git
    tags.datadoghq.com/git.commit.sha: c7634b395439fd79b3a74a69797b49d2f310067c
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        team: database
        tags.datadoghq.com/service: redis
        tags.datadoghq.com/version: '6.2'
      annotations:
        ad.datadoghq.com/redis.logs: '[{"source": "redis"}]'
        ad.datadoghq.com/redis.checks: "{\n  \"redisdb\": {\n  \"init_config\": {},\n\
          \  \"instances\": [{\"host\":\"%%host%%\", \"port\":6379}]\n  }\n}\n"
        tags.datadoghq.com/git.repository_url: https://github.com/Norawit2907/DataDog-Poc.git
        tags.datadoghq.com/git.commit.sha: c7634b395439fd79b3a74a69797b49d2f310067c
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
